import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import FavoriteIcon from "@mui/icons-material/Favorite";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Coco Marketplace</title>
        <meta name="description" content="Generated by Coco Marketplace" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/coco logo 1.png" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container1}>
          <div className={styles.children1}>
            <p className={styles.character1}>CREATE</p>
            <Image
              className={styles.plus}
              src="/plus sign hand 1.png"
              alt="plus"
              width={65}
              height={65}
            />
            <p className={styles.character1}>COLLECT</p>
          </div>
          <p className={styles.i}>A BINENCE SMART CHAIN NFT MARKETPALCE</p>
        </div>
        <div className={styles.container2}>
          <Image
            className={styles.dot}
            src="/Dot.png"
            alt="img1"
            width={310}
            height={170}
          />
          <Image
            style={{ borderRadius: "11px" }}
            src="/unsplash_E8Ufcyxz514.png"
            alt="img1"
            width={385}
            height={425}
          />
          <div className={styles.children2}>
            <div className={styles.child1}>
              <div className={styles.childchild}>
                <p>Creator</p>
                <div className={styles.cre}>
                  <Image
                    src="/Ellipse 95.png"
                    alt="img1"
                    width={20}
                    height={20}
                  />
                  <p>Arkhan17</p>
                </div>
              </div>
              <div className={styles.childchild}>
                <p>Owner</p>
                <div className={styles.own}>
                  <Image
                    src="/Ellipse 95.png"
                    alt="img1"
                    width={20}
                    height={20}
                  />
                  <p>Collection</p>
                </div>
              </div>
              <div className={styles.childchild}>
                <p>Collection</p>
                <div className={styles.collet}>
                  <Image
                    src="/Ellipse 95.png"
                    alt="img1"
                    width={20}
                    height={20}
                  />
                  <p>Arkhan17</p>
                </div>
              </div>
            </div>
            <p className={styles.child2}>Abstr Gradient NFT</p>
            <div className={styles.child3}>
              <div className={styles.ch1}>
                <p className={styles.char1}>Curent Bid</p>
                <p className={styles.char2}>0.25 BNB</p>
                <p className={styles.char3}>$182.00</p>
              </div>
              <div>
                <p className={styles.char1}>Auction ending in</p>
                <div className={styles.ch2}>
                  <p className={styles.char2}>12</p>
                  <p className={styles.char4}>H</p>
                  <p className={styles.char2}>43</p>
                  <p className={styles.char4}>M</p>
                  <p className={styles.char2}>42</p>
                  <p className={styles.char4}>S</p>
                </div>
              </div>
            </div>
            <button className={styles.btn1}>Bid Now</button>
          </div>
        </div>
        <div className={styles.container3}>
          <div className={styles.children3}>
            <p className={styles.char5}>HOT</p>
            <p className={styles.char6}>DROPS</p>
            <Image
              src="/Untitled_Artwork (4) 1.png"
              alt="img1"
              width={184}
              height={43}
            />
          </div>
          <div className={styles.children4}>
            <div className={styles.card}>
              <Image
                className={styles.cardimg}
                src="/unsplash_RnCPiXixooY.png"
                alt="img1"
                width={260}
                height={240}
              />
              <p className={styles.cardtitle}>Name of Collectible</p>
              <p className={styles.carddes}>Name of Collectible</p>
              <div className={styles.cardprice}>
                <Image src="/Group 255.png" alt="img1" width={20} height={20} />
                <p>0.25 BNB</p>
              </div>
              <div className={styles.cardbtn}>
                <button className={styles.cardbtn1}>3h 50m 2s</button>
                <button className={styles.cardbtn2}>Bid Now</button>
                <FavoriteIcon sx={{ color: " #F01866" }} />
              </div>
            </div>
            <div className={styles.card}>
              <Image
                className={styles.cardimg}
                src="/unsplash_RnCPiXixooY.png"
                alt="img1"
                width={260}
                height={240}
              />
              <p className={styles.cardtitle}>Name of Collectible</p>
              <p className={styles.carddes}>Name of Collectible</p>
              <div className={styles.cardprice}>
                <Image src="/Group 255.png" alt="img1" width={20} height={20} />
                <p>0.25 BNB</p>
              </div>
              <div className={styles.cardbtn}>
                <button className={styles.cardbtn1}>3h 50m 2s</button>
                <button className={styles.cardbtn2}>Bid Now</button>
                <FavoriteIcon sx={{ color: " #F01866" }} />
              </div>
            </div>
            <div className={styles.card}>
              <Image
                className={styles.cardimg}
                src="/unsplash_RnCPiXixooY.png"
                alt="img1"
                width={260}
                height={240}
              />
              <p className={styles.cardtitle}>Name of Collectible</p>
              <p className={styles.carddes}>Name of Collectible</p>
              <div className={styles.cardprice}>
                <Image src="/Group 255.png" alt="img1" width={20} height={20} />
                <p>0.25 BNB</p>
              </div>
              <div className={styles.cardbtn}>
                <button className={styles.cardbtn1}>3h 50m 2s</button>
                <button className={styles.cardbtn2}>Bid Now</button>
                <FavoriteIcon sx={{ color: " #F01866" }} />
              </div>
            </div>
          </div>
        </div>
        <div className={styles.container4}>
          <div className={styles.rank}>
            <p className={styles.ranktitle}>Top Collections</p>
            <div className={styles.rankdropbtn}>
              <p style={{ marginRight: "10px" }}>Last 7 days</p>
              <Image src="/Vector1.png" alt="img1" width={10} height={5} />
            </div>
            <div className={styles.rankcard}>
              <p className={styles.rankstt}>1</p>
              <div className={styles.rankcardavt1}>
                <Image
                  className={styles.rankcheck}
                  src="/Vector2.png"
                  alt="img1"
                  width={27}
                  height={27}
                />
                <Image
                  src="/unsplash_k0rVudBoB4c.png"
                  alt="img1"
                  width={60}
                  height={60}
                />
              </div>
              <div className={styles.rankbody}>
                <p className={styles.rankbodytitle}>CryptoFunks</p>
                <div className={styles.rankbodyprice}>
                  <Image
                    style={{ marginRight: "10px" }}
                    src="/Group 255.png"
                    alt="img1"
                    width={20}
                    height={20}
                  />
                  <p>19,769.39</p>
                </div>
              </div>
              <p className={styles.rankfooterc}>+26.52%</p>
            </div>
            <div className={styles.rankcard}>
              <p className={styles.rankstt}>2</p>
              <div className={styles.rankcardavt1}>
                <Image
                  src="/unsplash_k0rVudBoB4c2.png"
                  alt="img1"
                  width={60}
                  height={60}
                />
              </div>
              <div className={styles.rankbody}>
                <p className={styles.rankbodytitle}>Cryptix</p>
                <div className={styles.rankbodyprice}>
                  <Image
                    style={{ marginRight: "10px" }}
                    src="/Group 255.png"
                    alt="img1"
                    width={20}
                    height={20}
                  />
                  <p>9,769.39</p>
                </div>
              </div>
              <p className={styles.rankfootert}>-10.52%</p>
            </div>
            <div className={styles.rankcard}>
              <p className={styles.rankstt}>3</p>
              <div className={styles.rankcardavt1}>
                <Image
                  src="/unsplash_k0rVudBoB4c3.png"
                  alt="img1"
                  width={60}
                  height={60}
                />
              </div>
              <div className={styles.rankbody}>
                <p className={styles.rankbodytitle}>Frensware</p>
                <div className={styles.rankbodyprice}>
                  <Image
                    style={{ marginRight: "10px" }}
                    src="/Group 255.png"
                    alt="img1"
                    width={20}
                    height={20}
                  />
                  <p>19,769.39</p>
                </div>
              </div>
              <p className={styles.rankfooterc}>+26.52%</p>
            </div>
            <div className={styles.rankcard}>
              <p className={styles.rankstt}>4</p>
              <div className={styles.rankcardavt1}>
                <Image
                  src="/unsplash_k0rVudBoB4c4.png"
                  alt="img1"
                  width={60}
                  height={60}
                />
              </div>
              <div className={styles.rankbody}>
                <p className={styles.rankbodytitle}>Punk Art</p>
                <div className={styles.rankbodyprice}>
                  <Image
                    style={{ marginRight: "10px" }}
                    src="/Group 255.png"
                    alt="img1"
                    width={20}
                    height={20}
                  />
                  <p>19,769.39</p>
                </div>
              </div>
              <p className={styles.rankfooterc}>-6.52%</p>
            </div>
            <div className={styles.rankcard}>
              <p className={styles.rankstt}>5</p>
              <div className={styles.rankcardavt1}>
                <Image
                  src="/unsplash_k0rVudBoB4c5.png"
                  alt="img1"
                  width={60}
                  height={60}
                />
              </div>
              <div className={styles.rankbody}>
                <p className={styles.rankbodytitle}>Art Crypto</p>
                <div className={styles.rankbodyprice}>
                  <Image
                    style={{ marginRight: "10px" }}
                    src="/Group 255.png"
                    alt="img1"
                    width={20}
                    height={20}
                  />
                  <p>19,769.39</p>
                </div>
              </div>
              <p className={styles.rankfooterc}>+26.52%</p>
            </div>
          </div>
          <div className={styles.rank}>
            <p className={styles.ranktitle}>Top Sellers</p>
            <div className={styles.rankdropbtn}>
              <p style={{ marginRight: "10px" }}>Last 7 days</p>
              <Image src="/Vector1.png" alt="img1" width={10} height={5} />
            </div>
            <div className={styles.rankcard}>
              <p className={styles.rankstt}>1</p>
              <div className={styles.rankcardavt1}>
                <Image
                  className={styles.rankcheck}
                  src="/Vector2.png"
                  alt="img1"
                  width={27}
                  height={27}
                />
                <Image
                  src="/unsplash_k0rVudBoB4c.png"
                  alt="img1"
                  width={60}
                  height={60}
                />
              </div>
              <div className={styles.rankbody}>
                <p className={styles.rankbodytitle}>CryptoFunks</p>
                <div className={styles.rankbodyprice}>
                  <Image
                    style={{ marginRight: "10px" }}
                    src="/Group 255.png"
                    alt="img1"
                    width={20}
                    height={20}
                  />
                  <p>19,769.39</p>
                </div>
              </div>
              <p className={styles.rankfooterc}>+26.52%</p>
            </div>
            <div className={styles.rankcard}>
              <p className={styles.rankstt}>2</p>
              <div className={styles.rankcardavt1}>
                <Image
                  src="/unsplash_k0rVudBoB4c2.png"
                  alt="img1"
                  width={60}
                  height={60}
                />
              </div>
              <div className={styles.rankbody}>
                <p className={styles.rankbodytitle}>Cryptix</p>
                <div className={styles.rankbodyprice}>
                  <Image
                    style={{ marginRight: "10px" }}
                    src="/Group 255.png"
                    alt="img1"
                    width={20}
                    height={20}
                  />
                  <p>9,769.39</p>
                </div>
              </div>
              <p className={styles.rankfootert}>-10.52%</p>
            </div>
            <div className={styles.rankcard}>
              <p className={styles.rankstt}>3</p>
              <div className={styles.rankcardavt1}>
                <Image
                  src="/unsplash_k0rVudBoB4c3.png"
                  alt="img1"
                  width={60}
                  height={60}
                />
              </div>
              <div className={styles.rankbody}>
                <p className={styles.rankbodytitle}>Frensware</p>
                <div className={styles.rankbodyprice}>
                  <Image
                    style={{ marginRight: "10px" }}
                    src="/Group 255.png"
                    alt="img1"
                    width={20}
                    height={20}
                  />
                  <p>19,769.39</p>
                </div>
              </div>
              <p className={styles.rankfooterc}>+26.52%</p>
            </div>
            <div className={styles.rankcard}>
              <p className={styles.rankstt}>4</p>
              <div className={styles.rankcardavt1}>
                <Image
                  src="/unsplash_k0rVudBoB4c4.png"
                  alt="img1"
                  width={60}
                  height={60}
                />
              </div>
              <div className={styles.rankbody}>
                <p className={styles.rankbodytitle}>Punk Art</p>
                <div className={styles.rankbodyprice}>
                  <Image
                    style={{ marginRight: "10px" }}
                    src="/Group 255.png"
                    alt="img1"
                    width={20}
                    height={20}
                  />
                  <p>19,769.39</p>
                </div>
              </div>
              <p className={styles.rankfooterc}>-6.52%</p>
            </div>
            <div className={styles.rankcard}>
              <p className={styles.rankstt}>5</p>
              <div className={styles.rankcardavt1}>
                <Image
                  src="/unsplash_k0rVudBoB4c5.png"
                  alt="img1"
                  width={60}
                  height={60}
                />
              </div>
              <div className={styles.rankbody}>
                <p className={styles.rankbodytitle}>Art Crypto</p>
                <div className={styles.rankbodyprice}>
                  <Image
                    style={{ marginRight: "10px" }}
                    src="/Group 255.png"
                    alt="img1"
                    width={20}
                    height={20}
                  />
                  <p>19,769.39</p>
                </div>
              </div>
              <p className={styles.rankfooterc}>+26.52%</p>
            </div>
          </div>
          <div className={styles.rank}>
            <p className={styles.ranktitle}>Top Buyers</p>
            <div className={styles.rankdropbtn}>
              <p style={{ marginRight: "10px" }}>Last 7 days</p>
              <Image src="/Vector1.png" alt="img1" width={10} height={5} />
            </div>
            <div className={styles.rankcard}>
              <p className={styles.rankstt}>1</p>
              <div className={styles.rankcardavt1}>
                <Image
                  className={styles.rankcheck}
                  src="/Vector2.png"
                  alt="img1"
                  width={27}
                  height={27}
                />
                <Image
                  src="/unsplash_k0rVudBoB4c.png"
                  alt="img1"
                  width={60}
                  height={60}
                />
              </div>
              <div className={styles.rankbody}>
                <p className={styles.rankbodytitle}>CryptoFunks</p>
                <div className={styles.rankbodyprice}>
                  <Image
                    style={{ marginRight: "10px" }}
                    src="/Group 255.png"
                    alt="img1"
                    width={20}
                    height={20}
                  />
                  <p>19,769.39</p>
                </div>
              </div>
              <p className={styles.rankfooterc}>+26.52%</p>
            </div>
            <div className={styles.rankcard}>
              <p className={styles.rankstt}>2</p>
              <div className={styles.rankcardavt1}>
                <Image
                  src="/unsplash_k0rVudBoB4c2.png"
                  alt="img1"
                  width={60}
                  height={60}
                />
              </div>
              <div className={styles.rankbody}>
                <p className={styles.rankbodytitle}>Cryptix</p>
                <div className={styles.rankbodyprice}>
                  <Image
                    style={{ marginRight: "10px" }}
                    src="/Group 255.png"
                    alt="img1"
                    width={20}
                    height={20}
                  />
                  <p>9,769.39</p>
                </div>
              </div>
              <p className={styles.rankfootert}>-10.52%</p>
            </div>
            <div className={styles.rankcard}>
              <p className={styles.rankstt}>3</p>
              <div className={styles.rankcardavt1}>
                <Image
                  src="/unsplash_k0rVudBoB4c3.png"
                  alt="img1"
                  width={60}
                  height={60}
                />
              </div>
              <div className={styles.rankbody}>
                <p className={styles.rankbodytitle}>Frensware</p>
                <div className={styles.rankbodyprice}>
                  <Image
                    style={{ marginRight: "10px" }}
                    src="/Group 255.png"
                    alt="img1"
                    width={20}
                    height={20}
                  />
                  <p>19,769.39</p>
                </div>
              </div>
              <p className={styles.rankfooterc}>+26.52%</p>
            </div>
            <div className={styles.rankcard}>
              <p className={styles.rankstt}>4</p>
              <div className={styles.rankcardavt1}>
                <Image
                  src="/unsplash_k0rVudBoB4c4.png"
                  alt="img1"
                  width={60}
                  height={60}
                />
              </div>
              <div className={styles.rankbody}>
                <p className={styles.rankbodytitle}>Punk Art</p>
                <div className={styles.rankbodyprice}>
                  <Image
                    style={{ marginRight: "10px" }}
                    src="/Group 255.png"
                    alt="img1"
                    width={20}
                    height={20}
                  />
                  <p>19,769.39</p>
                </div>
              </div>
              <p className={styles.rankfooterc}>-6.52%</p>
            </div>
            <div className={styles.rankcard}>
              <p className={styles.rankstt}>5</p>
              <div className={styles.rankcardavt1}>
                <Image
                  src="/unsplash_k0rVudBoB4c5.png"
                  alt="img1"
                  width={60}
                  height={60}
                />
              </div>
              <div className={styles.rankbody}>
                <p className={styles.rankbodytitle}>Art Crypto</p>
                <div className={styles.rankbodyprice}>
                  <Image
                    style={{ marginRight: "10px" }}
                    src="/Group 255.png"
                    alt="img1"
                    width={20}
                    height={20}
                  />
                  <p>19,769.39</p>
                </div>
              </div>
              <p className={styles.rankfooterc}>+26.52%</p>
            </div>
          </div>
        </div>
        <div className={styles.container5}></div>
        <div className={styles.container6}></div>
        <div className={styles.container7}></div>
      </main>
    </>
  );
}
